name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        run: |
          docker login --username uchagani --password ${{secrets.GHCR_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/uchagani/caddy-docker-proxy-cloudflare:latest
          docker push ghcr.io/uchagani/caddy-docker-proxy-cloudflare:latest
